#!/usr/bin/ruby

#Author: Vatsaev Aslan (@avatsaev)
#Repository: https://github.com/avatsaev/mackeeper_blocker

#request root previleges in order to modify hosts file
if ENV["USER"] != "root"
  exec("sudo #{ENV['_']} #{ARGV.join(' ')}")
  exit
end

#initiate domain list array
mk_address_list = [
  "cleaningformac.com",
  "cleanmymac.com",
  "download.mac-install.com",
  "fixmymacos.com",
  "mac-cleaner.com",
  "mac-install.com",
  "maccleaner.com",
  "maccleaner.net",
  "mackeeper.com",
  "mackeeperapp.mackeeper.com",
  "mackeeperapp2.mackeeper.com",
  "mackeeperapp3.mackeeper.com",
  "macpaw.com",
  "macprotect.co",
  "safemac.co",
  "trustedmaccleaner.com"
]

#open hosts file in append mode
open('/etc/hosts', 'a') do |f|

  #for every domain name
  mk_address_list.each do |addr|
    p "Adding #{addr} to hosts file..."

    f.puts "127.0.0.1 #{addr}"
    p "✔︎ Done."
  end
  
  f.close
  
end

p "-----------"
p "✔︎ Script finished running."

exit
